INSERT INTO gostade VALUES('Jacinto Rodrigues','Albânia');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Alemanha');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Andorra');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Áustria');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Bélgica');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Bielorrúsia');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Bósnia e Herzegovina');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Bulgária');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Cazaquistão');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Chipre');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Croácia');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Dinamarca');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Eslováquia');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Eslovênia');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Espanha');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Estônia');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Finlândia');
INSERT INTO gostade VALUES('Jacinto Rodrigues','França');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Grécia');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Hungria');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Irlanda');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Islândia');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Itália');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Letônia');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Liechtenstein');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Lituânia');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Luxemburgo');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Malta');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Moldávia');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Mônaco');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Montenegro');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Noruega');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Países Baixos');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Polónia');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Portugal');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Checoslováquia');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Macedónia do Norte');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Inglaterra');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Escócia');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Irlanda do Norte');
INSERT INTO gostade VALUES('Jacinto Rodrigues','País de Gales');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Roménia');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Rússia');
INSERT INTO gostade VALUES('Jacinto Rodrigues','San Marino');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Sérvia');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Suécia');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Suíça');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Turquia');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Ucrânia');
INSERT INTO gostade VALUES('Jacinto Rodrigues','Vaticano');

INSERT INTO gostade VALUES('Abrantes de Metelo','Albânia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Alemanha');
INSERT INTO gostade VALUES('Abrantes de Metelo','Andorra');
INSERT INTO gostade VALUES('Abrantes de Metelo','Áustria');
INSERT INTO gostade VALUES('Abrantes de Metelo','Bélgica');
INSERT INTO gostade VALUES('Abrantes de Metelo','Bielorrúsia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Bósnia e Herzegovina');
INSERT INTO gostade VALUES('Abrantes de Metelo','Bulgária');
INSERT INTO gostade VALUES('Abrantes de Metelo','Cazaquistão');
INSERT INTO gostade VALUES('Abrantes de Metelo','Chipre');
INSERT INTO gostade VALUES('Abrantes de Metelo','Croácia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Dinamarca');
INSERT INTO gostade VALUES('Abrantes de Metelo','Eslováquia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Eslovênia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Espanha');
INSERT INTO gostade VALUES('Abrantes de Metelo','Estônia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Finlândia');
INSERT INTO gostade VALUES('Abrantes de Metelo','França');
INSERT INTO gostade VALUES('Abrantes de Metelo','Grécia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Hungria');
INSERT INTO gostade VALUES('Abrantes de Metelo','Irlanda');
INSERT INTO gostade VALUES('Abrantes de Metelo','Islândia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Itália');
INSERT INTO gostade VALUES('Abrantes de Metelo','Letônia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Liechtenstein');
INSERT INTO gostade VALUES('Abrantes de Metelo','Lituânia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Luxemburgo');
INSERT INTO gostade VALUES('Abrantes de Metelo','Malta');
INSERT INTO gostade VALUES('Abrantes de Metelo','Moldávia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Mônaco');
INSERT INTO gostade VALUES('Abrantes de Metelo','Montenegro');
INSERT INTO gostade VALUES('Abrantes de Metelo','Noruega');
INSERT INTO gostade VALUES('Abrantes de Metelo','Países Baixos');
INSERT INTO gostade VALUES('Abrantes de Metelo','Polónia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Portugal');
INSERT INTO gostade VALUES('Abrantes de Metelo','Checoslováquia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Macedónia do Norte');
INSERT INTO gostade VALUES('Abrantes de Metelo','Inglaterra');
INSERT INTO gostade VALUES('Abrantes de Metelo','Escócia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Irlanda do Norte');
INSERT INTO gostade VALUES('Abrantes de Metelo','País de Gales');
INSERT INTO gostade VALUES('Abrantes de Metelo','Roménia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Rússia');
INSERT INTO gostade VALUES('Abrantes de Metelo','San Marino');
INSERT INTO gostade VALUES('Abrantes de Metelo','Sérvia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Suécia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Suíça');
INSERT INTO gostade VALUES('Abrantes de Metelo','Turquia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Ucrânia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Vaticano');

INSERT INTO gostade VALUES('Jennifer Daynight','Albânia');
INSERT INTO gostade VALUES('Jennifer Daynight','Alemanha');
INSERT INTO gostade VALUES('Jennifer Daynight','Andorra');
INSERT INTO gostade VALUES('Jennifer Daynight','Áustria');
INSERT INTO gostade VALUES('Jennifer Daynight','Bélgica');
INSERT INTO gostade VALUES('Jennifer Daynight','Bielorrúsia');
INSERT INTO gostade VALUES('Jennifer Daynight','Bósnia e Herzegovina');
INSERT INTO gostade VALUES('Jennifer Daynight','Bulgária');
INSERT INTO gostade VALUES('Jennifer Daynight','Cazaquistão');
INSERT INTO gostade VALUES('Jennifer Daynight','Chipre');
INSERT INTO gostade VALUES('Jennifer Daynight','Croácia');
INSERT INTO gostade VALUES('Jennifer Daynight','Dinamarca');
INSERT INTO gostade VALUES('Jennifer Daynight','Eslováquia');
INSERT INTO gostade VALUES('Jennifer Daynight','Eslovênia');
INSERT INTO gostade VALUES('Jennifer Daynight','Espanha');
INSERT INTO gostade VALUES('Jennifer Daynight','Estônia');
INSERT INTO gostade VALUES('Jennifer Daynight','Finlândia');
INSERT INTO gostade VALUES('Jennifer Daynight','França');
INSERT INTO gostade VALUES('Jennifer Daynight','Grécia');
INSERT INTO gostade VALUES('Jennifer Daynight','Hungria');
INSERT INTO gostade VALUES('Jennifer Daynight','Irlanda');
INSERT INTO gostade VALUES('Jennifer Daynight','Islândia');
INSERT INTO gostade VALUES('Jennifer Daynight','Itália');
INSERT INTO gostade VALUES('Jennifer Daynight','Letônia');
INSERT INTO gostade VALUES('Jennifer Daynight','Liechtenstein');
INSERT INTO gostade VALUES('Jennifer Daynight','Lituânia');
INSERT INTO gostade VALUES('Jennifer Daynight','Luxemburgo');
INSERT INTO gostade VALUES('Jennifer Daynight','Malta');
INSERT INTO gostade VALUES('Jennifer Daynight','Moldávia');
INSERT INTO gostade VALUES('Jennifer Daynight','Mônaco');
INSERT INTO gostade VALUES('Jennifer Daynight','Montenegro');
INSERT INTO gostade VALUES('Jennifer Daynight','Noruega');
INSERT INTO gostade VALUES('Jennifer Daynight','Países Baixos');
INSERT INTO gostade VALUES('Jennifer Daynight','Polónia');
INSERT INTO gostade VALUES('Jennifer Daynight','Portugal');
INSERT INTO gostade VALUES('Jennifer Daynight','Checoslováquia');
INSERT INTO gostade VALUES('Jennifer Daynight','Macedónia do Norte');
INSERT INTO gostade VALUES('Jennifer Daynight','Inglaterra');
INSERT INTO gostade VALUES('Jennifer Daynight','Escócia');
INSERT INTO gostade VALUES('Jennifer Daynight','Irlanda do Norte');
INSERT INTO gostade VALUES('Jennifer Daynight','País de Gales');
INSERT INTO gostade VALUES('Jennifer Daynight','Roménia');
INSERT INTO gostade VALUES('Jennifer Daynight','Rússia');
INSERT INTO gostade VALUES('Jennifer Daynight','San Marino');
INSERT INTO gostade VALUES('Jennifer Daynight','Sérvia');
INSERT INTO gostade VALUES('Jennifer Daynight','Suécia');
INSERT INTO gostade VALUES('Jennifer Daynight','Suíça');
INSERT INTO gostade VALUES('Jennifer Daynight','Turquia');
INSERT INTO gostade VALUES('Jennifer Daynight','Ucrânia');
INSERT INTO gostade VALUES('Jennifer Daynight','Vaticano');

INSERT INTO gostade VALUES('Alice Rodrigues','Albânia');
INSERT INTO gostade VALUES('Alice Rodrigues','Alemanha');
INSERT INTO gostade VALUES('Alice Rodrigues','Andorra');
INSERT INTO gostade VALUES('Alice Rodrigues','Áustria');
INSERT INTO gostade VALUES('Alice Rodrigues','Bélgica');
INSERT INTO gostade VALUES('Alice Rodrigues','Bielorrúsia');
INSERT INTO gostade VALUES('Alice Rodrigues','Bósnia e Herzegovina');
INSERT INTO gostade VALUES('Alice Rodrigues','Bulgária');
INSERT INTO gostade VALUES('Alice Rodrigues','Cazaquistão');
INSERT INTO gostade VALUES('Alice Rodrigues','Chipre');
INSERT INTO gostade VALUES('Alice Rodrigues','Croácia');
INSERT INTO gostade VALUES('Alice Rodrigues','Dinamarca');
INSERT INTO gostade VALUES('Alice Rodrigues','Eslováquia');
INSERT INTO gostade VALUES('Alice Rodrigues','Eslovênia');
INSERT INTO gostade VALUES('Alice Rodrigues','Espanha');
INSERT INTO gostade VALUES('Alice Rodrigues','Estônia');
INSERT INTO gostade VALUES('Alice Rodrigues','Finlândia');
INSERT INTO gostade VALUES('Alice Rodrigues','França');
INSERT INTO gostade VALUES('Alice Rodrigues','Grécia');
INSERT INTO gostade VALUES('Alice Rodrigues','Hungria');
INSERT INTO gostade VALUES('Alice Rodrigues','Irlanda');
INSERT INTO gostade VALUES('Alice Rodrigues','Islândia');
INSERT INTO gostade VALUES('Alice Rodrigues','Itália');
INSERT INTO gostade VALUES('Alice Rodrigues','Letônia');
INSERT INTO gostade VALUES('Alice Rodrigues','Liechtenstein');
INSERT INTO gostade VALUES('Alice Rodrigues','Lituânia');
INSERT INTO gostade VALUES('Alice Rodrigues','Luxemburgo');
INSERT INTO gostade VALUES('Alice Rodrigues','Malta');
INSERT INTO gostade VALUES('Alice Rodrigues','Moldávia');
INSERT INTO gostade VALUES('Alice Rodrigues','Mônaco');
INSERT INTO gostade VALUES('Alice Rodrigues','Montenegro');
INSERT INTO gostade VALUES('Alice Rodrigues','Noruega');
INSERT INTO gostade VALUES('Alice Rodrigues','Países Baixos');
INSERT INTO gostade VALUES('Alice Rodrigues','Polónia');
INSERT INTO gostade VALUES('Alice Rodrigues','Portugal');
INSERT INTO gostade VALUES('Alice Rodrigues','Checoslováquia');
INSERT INTO gostade VALUES('Alice Rodrigues','Macedónia do Norte');
INSERT INTO gostade VALUES('Alice Rodrigues','Inglaterra');
INSERT INTO gostade VALUES('Alice Rodrigues','Escócia');
INSERT INTO gostade VALUES('Alice Rodrigues','Irlanda do Norte');
INSERT INTO gostade VALUES('Alice Rodrigues','País de Gales');
INSERT INTO gostade VALUES('Alice Rodrigues','Roménia');
INSERT INTO gostade VALUES('Alice Rodrigues','Rússia');
INSERT INTO gostade VALUES('Alice Rodrigues','San Marino');
INSERT INTO gostade VALUES('Alice Rodrigues','Sérvia');
INSERT INTO gostade VALUES('Alice Rodrigues','Suécia');
INSERT INTO gostade VALUES('Alice Rodrigues','Suíça');
INSERT INTO gostade VALUES('Alice Rodrigues','Turquia');
INSERT INTO gostade VALUES('Alice Rodrigues','Ucrânia');
INSERT INTO gostade VALUES('Alice Rodrigues','Vaticano');

INSERT INTO gostade VALUES('Joana Vinagre','Albânia');
INSERT INTO gostade VALUES('Joana Vinagre','Alemanha');
INSERT INTO gostade VALUES('Joana Vinagre','Andorra');
INSERT INTO gostade VALUES('Joana Vinagre','Áustria');
INSERT INTO gostade VALUES('Joana Vinagre','Bélgica');
INSERT INTO gostade VALUES('Joana Vinagre','Bielorrúsia');
INSERT INTO gostade VALUES('Joana Vinagre','Bósnia e Herzegovina');
INSERT INTO gostade VALUES('Joana Vinagre','Bulgária');
INSERT INTO gostade VALUES('Joana Vinagre','Cazaquistão');
INSERT INTO gostade VALUES('Joana Vinagre','Chipre');
INSERT INTO gostade VALUES('Joana Vinagre','Croácia');
INSERT INTO gostade VALUES('Joana Vinagre','Dinamarca');
INSERT INTO gostade VALUES('Joana Vinagre','Eslováquia');
INSERT INTO gostade VALUES('Joana Vinagre','Eslovênia');
INSERT INTO gostade VALUES('Joana Vinagre','Espanha');
INSERT INTO gostade VALUES('Joana Vinagre','Estônia');
INSERT INTO gostade VALUES('Joana Vinagre','Finlândia');
INSERT INTO gostade VALUES('Joana Vinagre','França');
INSERT INTO gostade VALUES('Joana Vinagre','Grécia');
INSERT INTO gostade VALUES('Joana Vinagre','Hungria');
INSERT INTO gostade VALUES('Joana Vinagre','Irlanda');
INSERT INTO gostade VALUES('Joana Vinagre','Islândia');
INSERT INTO gostade VALUES('Joana Vinagre','Itália');
INSERT INTO gostade VALUES('Joana Vinagre','Letônia');
INSERT INTO gostade VALUES('Joana Vinagre','Liechtenstein');
INSERT INTO gostade VALUES('Joana Vinagre','Lituânia');
INSERT INTO gostade VALUES('Joana Vinagre','Luxemburgo');
INSERT INTO gostade VALUES('Joana Vinagre','Malta');
INSERT INTO gostade VALUES('Joana Vinagre','Moldávia');
INSERT INTO gostade VALUES('Joana Vinagre','Mônaco');
INSERT INTO gostade VALUES('Joana Vinagre','Montenegro');
INSERT INTO gostade VALUES('Joana Vinagre','Noruega');
INSERT INTO gostade VALUES('Joana Vinagre','Países Baixos');
INSERT INTO gostade VALUES('Joana Vinagre','Polónia');
INSERT INTO gostade VALUES('Joana Vinagre','Portugal');
INSERT INTO gostade VALUES('Joana Vinagre','Checoslováquia');
INSERT INTO gostade VALUES('Joana Vinagre','Macedónia do Norte');
INSERT INTO gostade VALUES('Joana Vinagre','Inglaterra');
INSERT INTO gostade VALUES('Joana Vinagre','Escócia');
INSERT INTO gostade VALUES('Joana Vinagre','Irlanda do Norte');
INSERT INTO gostade VALUES('Joana Vinagre','País de Gales');
INSERT INTO gostade VALUES('Joana Vinagre','Roménia');
INSERT INTO gostade VALUES('Joana Vinagre','Rússia');
INSERT INTO gostade VALUES('Joana Vinagre','San Marino');
INSERT INTO gostade VALUES('Joana Vinagre','Sérvia');
INSERT INTO gostade VALUES('Joana Vinagre','Suécia');
INSERT INTO gostade VALUES('Joana Vinagre','Suíça');
INSERT INTO gostade VALUES('Joana Vinagre','Turquia');
INSERT INTO gostade VALUES('Joana Vinagre','Ucrânia');
INSERT INTO gostade VALUES('Joana Vinagre','Vaticano');

INSERT INTO gostade VALUES('Josímar Perro','Alemanha');
INSERT INTO gostade VALUES('Josímar Perro','Áustria');
INSERT INTO gostade VALUES('Josímar Perro','Bélgica');
INSERT INTO gostade VALUES('Josímar Perro','Bulgária');
INSERT INTO gostade VALUES('Josímar Perro','Chéquia');
INSERT INTO gostade VALUES('Josímar Perro','Chipre');
INSERT INTO gostade VALUES('Josímar Perro','Croácia');
INSERT INTO gostade VALUES('Josímar Perro','Dinamarca');
INSERT INTO gostade VALUES('Josímar Perro','Eslováquia');
INSERT INTO gostade VALUES('Josímar Perro','Eslovénia');
INSERT INTO gostade VALUES('Josímar Perro','Espanha');
INSERT INTO gostade VALUES('Josímar Perro','Estónia');
INSERT INTO gostade VALUES('Josímar Perro','Finlândia');
INSERT INTO gostade VALUES('Josímar Perro','França');
INSERT INTO gostade VALUES('Josímar Perro','Grécia');
INSERT INTO gostade VALUES('Josímar Perro','Hungria');
INSERT INTO gostade VALUES('Josímar Perro','Irlanda');
INSERT INTO gostade VALUES('Josímar Perro','Itália');
INSERT INTO gostade VALUES('Josímar Perro','Letónia');
INSERT INTO gostade VALUES('Josímar Perro','Lituânia');
INSERT INTO gostade VALUES('Josímar Perro','Luxemburgo');
INSERT INTO gostade VALUES('Josímar Perro','Malta');
INSERT INTO gostade VALUES('Josímar Perro','Países Baixos');
INSERT INTO gostade VALUES('Josímar Perro','Polónia');
INSERT INTO gostade VALUES('Josímar Perro','Portugal');
INSERT INTO gostade VALUES('Josímar Perro','Roménia');
INSERT INTO gostade VALUES('Josímar Perro','Suécia');

INSERT INTO gostade VALUES('Antoine Griezmann','Alemanha');
INSERT INTO gostade VALUES('Antoine Griezmann','Áustria');
INSERT INTO gostade VALUES('Antoine Griezmann','Bélgica');
INSERT INTO gostade VALUES('Antoine Griezmann','Bulgária');
INSERT INTO gostade VALUES('Antoine Griezmann','Chéquia');
INSERT INTO gostade VALUES('Antoine Griezmann','Chipre');
INSERT INTO gostade VALUES('Antoine Griezmann','Croácia');
INSERT INTO gostade VALUES('Antoine Griezmann','Dinamarca');
INSERT INTO gostade VALUES('Antoine Griezmann','Eslováquia');
INSERT INTO gostade VALUES('Antoine Griezmann','Eslovénia');
INSERT INTO gostade VALUES('Antoine Griezmann','Espanha');
INSERT INTO gostade VALUES('Antoine Griezmann','Estónia');
INSERT INTO gostade VALUES('Antoine Griezmann','Finlândia');
INSERT INTO gostade VALUES('Antoine Griezmann','França');
INSERT INTO gostade VALUES('Antoine Griezmann','Grécia');
INSERT INTO gostade VALUES('Antoine Griezmann','Hungria');
INSERT INTO gostade VALUES('Antoine Griezmann','Irlanda');
INSERT INTO gostade VALUES('Antoine Griezmann','Itália');
INSERT INTO gostade VALUES('Antoine Griezmann','Letónia');
INSERT INTO gostade VALUES('Antoine Griezmann','Lituânia');
INSERT INTO gostade VALUES('Antoine Griezmann','Luxemburgo');
INSERT INTO gostade VALUES('Antoine Griezmann','Malta');
INSERT INTO gostade VALUES('Antoine Griezmann','Países Baixos');
INSERT INTO gostade VALUES('Antoine Griezmann','Polónia');
INSERT INTO gostade VALUES('Antoine Griezmann','Portugal');
INSERT INTO gostade VALUES('Antoine Griezmann','Roménia');
INSERT INTO gostade VALUES('Antoine Griezmann','Suécia');

INSERT INTO gostade VALUES('Cristiano Ronaldo','Alemanha');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Áustria');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Bélgica');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Bulgária');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Chéquia');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Chipre');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Croácia');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Dinamarca');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Eslováquia');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Eslovénia');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Espanha');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Estónia');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Finlândia');
INSERT INTO gostade VALUES('Cristiano Ronaldo','França');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Grécia');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Hungria');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Irlanda');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Itália');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Letónia');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Lituânia');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Luxemburgo');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Malta');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Países Baixos');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Polónia');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Portugal');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Roménia');
INSERT INTO gostade VALUES('Cristiano Ronaldo','Suécia');

INSERT INTO gostade VALUES('Cristina Ferreira','Alemanha');
INSERT INTO gostade VALUES('Cristina Ferreira','Áustria');
INSERT INTO gostade VALUES('Cristina Ferreira','Bélgica');
INSERT INTO gostade VALUES('Cristina Ferreira','Bulgária');
INSERT INTO gostade VALUES('Cristina Ferreira','Chéquia');
INSERT INTO gostade VALUES('Cristina Ferreira','Chipre');
INSERT INTO gostade VALUES('Cristina Ferreira','Croácia');
INSERT INTO gostade VALUES('Cristina Ferreira','Dinamarca');
INSERT INTO gostade VALUES('Cristina Ferreira','Eslováquia');
INSERT INTO gostade VALUES('Cristina Ferreira','Eslovénia');
INSERT INTO gostade VALUES('Cristina Ferreira','Espanha');
INSERT INTO gostade VALUES('Cristina Ferreira','Estónia');
INSERT INTO gostade VALUES('Cristina Ferreira','Finlândia');
INSERT INTO gostade VALUES('Cristina Ferreira','França');
INSERT INTO gostade VALUES('Cristina Ferreira','Grécia');
INSERT INTO gostade VALUES('Cristina Ferreira','Hungria');
INSERT INTO gostade VALUES('Cristina Ferreira','Irlanda');
INSERT INTO gostade VALUES('Cristina Ferreira','Itália');
INSERT INTO gostade VALUES('Cristina Ferreira','Letónia');
INSERT INTO gostade VALUES('Cristina Ferreira','Lituânia');
INSERT INTO gostade VALUES('Cristina Ferreira','Luxemburgo');
INSERT INTO gostade VALUES('Cristina Ferreira','Malta');
INSERT INTO gostade VALUES('Cristina Ferreira','Países Baixos');
INSERT INTO gostade VALUES('Cristina Ferreira','Polónia');
INSERT INTO gostade VALUES('Cristina Ferreira','Portugal');
INSERT INTO gostade VALUES('Cristina Ferreira','Roménia');
INSERT INTO gostade VALUES('Cristina Ferreira','Suécia');

INSERT INTO gostade VALUES('Sofia Ribeiro','Alemanha');
INSERT INTO gostade VALUES('Sofia Ribeiro','Áustria');
INSERT INTO gostade VALUES('Sofia Ribeiro','Bélgica');
INSERT INTO gostade VALUES('Sofia Ribeiro','Bulgária');
INSERT INTO gostade VALUES('Sofia Ribeiro','Chéquia');
INSERT INTO gostade VALUES('Sofia Ribeiro','Chipre');
INSERT INTO gostade VALUES('Sofia Ribeiro','Croácia');
INSERT INTO gostade VALUES('Sofia Ribeiro','Dinamarca');
INSERT INTO gostade VALUES('Sofia Ribeiro','Eslováquia');
INSERT INTO gostade VALUES('Sofia Ribeiro','Eslovénia');
INSERT INTO gostade VALUES('Sofia Ribeiro','Espanha');
INSERT INTO gostade VALUES('Sofia Ribeiro','Estónia');
INSERT INTO gostade VALUES('Sofia Ribeiro','Finlândia');
INSERT INTO gostade VALUES('Sofia Ribeiro','França');
INSERT INTO gostade VALUES('Sofia Ribeiro','Grécia');
INSERT INTO gostade VALUES('Sofia Ribeiro','Hungria');
INSERT INTO gostade VALUES('Sofia Ribeiro','Irlanda');
INSERT INTO gostade VALUES('Sofia Ribeiro','Itália');
INSERT INTO gostade VALUES('Sofia Ribeiro','Letónia');
INSERT INTO gostade VALUES('Sofia Ribeiro','Lituânia');
INSERT INTO gostade VALUES('Sofia Ribeiro','Luxemburgo');
INSERT INTO gostade VALUES('Sofia Ribeiro','Malta');
INSERT INTO gostade VALUES('Sofia Ribeiro','Países Baixos');
INSERT INTO gostade VALUES('Sofia Ribeiro','Polónia');
INSERT INTO gostade VALUES('Sofia Ribeiro','Portugal');
INSERT INTO gostade VALUES('Sofia Ribeiro','Roménia');
INSERT INTO gostade VALUES('Sofia Ribeiro','Suécia');

INSERT INTO gostade VALUES('Luís Fernandes','Portugal');
INSERT INTO gostade VALUES('Luís Fernandes','Angola');
INSERT INTO gostade VALUES('Luís Fernandes','Brasil');
INSERT INTO gostade VALUES('Luís Fernandes','Cabo Verde');
INSERT INTO gostade VALUES('Luís Fernandes','Guiné-Bissau');
INSERT INTO gostade VALUES('Luís Fernandes','Guiné Equatorial');
INSERT INTO gostade VALUES('Luís Fernandes','Moçambique');
INSERT INTO gostade VALUES('Luís Fernandes','São Tomé e Príncipe');
INSERT INTO gostade VALUES('Luís Fernandes','Timor-Leste');
INSERT INTO gostade VALUES('Luís Fernandes','Macau');

INSERT INTO gostade VALUES('Roberto Gago','Portugal');
INSERT INTO gostade VALUES('Roberto Gago','Angola');
INSERT INTO gostade VALUES('Roberto Gago','Brasil');
INSERT INTO gostade VALUES('Roberto Gago','Cabo Verde');
INSERT INTO gostade VALUES('Roberto Gago','Guiné-Bissau');
INSERT INTO gostade VALUES('Roberto Gago','Guiné Equatorial');
INSERT INTO gostade VALUES('Roberto Gago','Moçambique');
INSERT INTO gostade VALUES('Roberto Gago','São Tomé e Príncipe');
INSERT INTO gostade VALUES('Roberto Gago','Timor-Leste');
INSERT INTO gostade VALUES('Roberto Gago','Macau');

INSERT INTO gostade VALUES('Képler Ferreira','Portugal');
INSERT INTO gostade VALUES('Képler Ferreira','Angola');
INSERT INTO gostade VALUES('Képler Ferreira','Brasil');
INSERT INTO gostade VALUES('Képler Ferreira','Cabo Verde');
INSERT INTO gostade VALUES('Képler Ferreira','Guiné-Bissau');
INSERT INTO gostade VALUES('Képler Ferreira','Guiné Equatorial');
INSERT INTO gostade VALUES('Képler Ferreira','Moçambique');
INSERT INTO gostade VALUES('Képler Ferreira','São Tomé e Príncipe');
INSERT INTO gostade VALUES('Képler Ferreira','Timor-Leste');
INSERT INTO gostade VALUES('Képler Ferreira','Macau');

INSERT INTO gostade VALUES('Ederson Moraes','Portugal');
INSERT INTO gostade VALUES('Ederson Moraes','Angola');
INSERT INTO gostade VALUES('Ederson Moraes','Brasil');
INSERT INTO gostade VALUES('Ederson Moraes','Cabo Verde');
INSERT INTO gostade VALUES('Ederson Moraes','Guiné-Bissau');
INSERT INTO gostade VALUES('Ederson Moraes','Guiné Equatorial');
INSERT INTO gostade VALUES('Ederson Moraes','Moçambique');
INSERT INTO gostade VALUES('Ederson Moraes','São Tomé e Príncipe');
INSERT INTO gostade VALUES('Ederson Moraes','Timor-Leste');
INSERT INTO gostade VALUES('Ederson Moraes','Macau');

INSERT INTO gostade VALUES('Liedson Muniz','Portugal');
INSERT INTO gostade VALUES('Liedson Muniz','Angola');
INSERT INTO gostade VALUES('Liedson Muniz','Brasil');
INSERT INTO gostade VALUES('Liedson Muniz','Cabo Verde');
INSERT INTO gostade VALUES('Liedson Muniz','Guiné-Bissau');
INSERT INTO gostade VALUES('Liedson Muniz','Guiné Equatorial');
INSERT INTO gostade VALUES('Liedson Muniz','Moçambique');
INSERT INTO gostade VALUES('Liedson Muniz','São Tomé e Príncipe');
INSERT INTO gostade VALUES('Liedson Muniz','Timor-Leste');
INSERT INTO gostade VALUES('Liedson Muniz','Macau');
