INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Albânia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Alemanha');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Andorra');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Áustria');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Bélgica');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Bielorrúsia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Bósnia e Herzegovina');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Bulgária');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Cazaquistão');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Chipre');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Croácia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Dinamarca');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Eslováquia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Eslovênia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Espanha');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Estônia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Finlândia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','França');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Grécia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Hungria');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Irlanda');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Islândia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Itália');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Letônia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Liechtenstein');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Lituânia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Luxemburgo');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Malta');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Moldávia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Mônaco');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Montenegro');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Noruega');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Países Baixos');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Polónia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Portugal');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Checoslováquia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Macedónia do Norte');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Inglaterra');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Escócia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Irlanda do Norte');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','País de Gales');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Roménia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Rússia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','San Marino');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Sérvia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Suécia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Suíça');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Turquia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Ucrânia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Vaticano');
