INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Albânia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Alemanha');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Andorra');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Áustria');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Bélgica');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Bielorrúsia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Bósnia e Herzegovina');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Bulgária');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Cazaquistão');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Chipre');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Croácia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Dinamarca');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Eslováquia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Eslovênia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Espanha');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Estônia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Finlândia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','França');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Grécia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Hungria');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Irlanda');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Islândia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Itália');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Letônia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Liechtenstein');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Lituânia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Luxemburgo');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Malta');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Moldávia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Mônaco');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Montenegro');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Noruega');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Países Baixos');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Polónia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Portugal');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Checoslováquia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Macedónia do Norte');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Inglaterra');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Escócia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Irlanda do Norte');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','País de Gales');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Roménia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Rússia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','San Marino');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Sérvia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Suécia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Suíça');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Turquia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Ucrânia');
INSERT INTO gostade VALUES('Jacinto Leite Aquino Rego','Vaticano');

INSERT INTO gostade VALUES('Abrantes de Metelo','Albânia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Alemanha');
INSERT INTO gostade VALUES('Abrantes de Metelo','Andorra');
INSERT INTO gostade VALUES('Abrantes de Metelo','Áustria');
INSERT INTO gostade VALUES('Abrantes de Metelo','Bélgica');
INSERT INTO gostade VALUES('Abrantes de Metelo','Bielorrúsia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Bósnia e Herzegovina');
INSERT INTO gostade VALUES('Abrantes de Metelo','Bulgária');
INSERT INTO gostade VALUES('Abrantes de Metelo','Cazaquistão');
INSERT INTO gostade VALUES('Abrantes de Metelo','Chipre');
INSERT INTO gostade VALUES('Abrantes de Metelo','Croácia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Dinamarca');
INSERT INTO gostade VALUES('Abrantes de Metelo','Eslováquia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Eslovênia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Espanha');
INSERT INTO gostade VALUES('Abrantes de Metelo','Estônia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Finlândia');
INSERT INTO gostade VALUES('Abrantes de Metelo','França');
INSERT INTO gostade VALUES('Abrantes de Metelo','Grécia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Hungria');
INSERT INTO gostade VALUES('Abrantes de Metelo','Irlanda');
INSERT INTO gostade VALUES('Abrantes de Metelo','Islândia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Itália');
INSERT INTO gostade VALUES('Abrantes de Metelo','Letônia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Liechtenstein');
INSERT INTO gostade VALUES('Abrantes de Metelo','Lituânia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Luxemburgo');
INSERT INTO gostade VALUES('Abrantes de Metelo','Malta');
INSERT INTO gostade VALUES('Abrantes de Metelo','Moldávia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Mônaco');
INSERT INTO gostade VALUES('Abrantes de Metelo','Montenegro');
INSERT INTO gostade VALUES('Abrantes de Metelo','Noruega');
INSERT INTO gostade VALUES('Abrantes de Metelo','Países Baixos');
INSERT INTO gostade VALUES('Abrantes de Metelo','Polónia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Portugal');
INSERT INTO gostade VALUES('Abrantes de Metelo','Checoslováquia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Macedónia do Norte');
INSERT INTO gostade VALUES('Abrantes de Metelo','Inglaterra');
INSERT INTO gostade VALUES('Abrantes de Metelo','Escócia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Irlanda do Norte');
INSERT INTO gostade VALUES('Abrantes de Metelo','País de Gales');
INSERT INTO gostade VALUES('Abrantes de Metelo','Roménia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Rússia');
INSERT INTO gostade VALUES('Abrantes de Metelo','San Marino');
INSERT INTO gostade VALUES('Abrantes de Metelo','Sérvia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Suécia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Suíça');
INSERT INTO gostade VALUES('Abrantes de Metelo','Turquia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Ucrânia');
INSERT INTO gostade VALUES('Abrantes de Metelo','Vaticano');
